version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306  
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_PASSWORD
  app:
    build:
      dockerfile: Dockerfile.local
    ports:
    - 8080:8080
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      TZ: 'Asia/Tokyo'
    volumes:
      - ./:/app
  redis:
    image: "redis:7.2.1"
    ports:
      - "6379:6379"   
