development:
  dialect: mysql
  datasource: root:root@(127.0.0.1:3306)/task?parseTime=true
  dir: migrations
  table: migrations

production:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@(${DB_HOST}:3306)/task?parseTime=true
  dir: migrations
  table: migrations
