version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306  
  app:
    build:
      dockerfile: Dockerfile.local
    ports:
    - 8080:8080
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      TZ: 'Asia/Tokyo'
    volumes:
      - ./:/app
