name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: db start
        run: |
          go install github.com/rubenv/sql-migrate/...@latest
          docker compose up -d db
        working-directory: ./backend
      - name: db migrate
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root -proot; do
            sleep 2
          done
          sql-migrate up -env=test
        working-directory: ./backend
      - name: Test
        run: go test -v ./...
        working-directory: ./backend
